<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P420100I6.jpg ",93,261);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P420100I6.jpg";
$z[1][4]['text']="郑州一汽大众4S店保洁";
$z[1][4]['width']="720";
$z[1][4]['height']="560";
$z[2]=Array("img"," /uploads/allimg/1804/1-1P420100K5.jpg ",263,431);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/1804/1-1P420100K5.jpg";
$z[2][4]['text']="郑州一汽大众4S店保洁";
$z[2][4]['width']="720";
$z[2][4]['height']="560";
$z[3]=Array("img"," /uploads/allimg/1804/1-1P420100K5-50.jpg ",433,607);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/1804/1-1P420100K5-50.jpg";
$z[3][4]['text']="郑州一汽大众4S店保洁";
$z[3][4]['width']="720";
$z[3][4]['height']="560";
$z[4]=Array("img"," /uploads/allimg/1804/1-1P420100K5-51.jpg ",609,783);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/1804/1-1P420100K5-51.jpg";
$z[4][4]['text']="郑州一汽大众4S店保洁";
$z[4][4]['width']="720";
$z[4][4]['height']="560";

?>