{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/1804/1-1P420100I6.jpg' text='郑州一汽大众4S店保洁' width='720' height='560'} /uploads/allimg/1804/1-1P420100I6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420100K5.jpg' text='郑州一汽大众4S店保洁' width='720' height='560'} /uploads/allimg/1804/1-1P420100K5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420100K5-50.jpg' text='郑州一汽大众4S店保洁' width='720' height='560'} /uploads/allimg/1804/1-1P420100K5-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420100K5-51.jpg' text='郑州一汽大众4S店保洁' width='720' height='560'} /uploads/allimg/1804/1-1P420100K5-51.jpg {/dede:img}
