{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103032.jpg' text='郑州惠民中学保洁' width='500' height='332'} /uploads/allimg/1804/1-1P420103032.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103033.jpg' text='郑州惠民中学保洁' width='500' height='332'} /uploads/allimg/1804/1-1P420103033.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103033-50.jpg' text='郑州惠民中学保洁' width='500' height='332'} /uploads/allimg/1804/1-1P420103033-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103033-51.jpg' text='郑州惠民中学保洁' width='591' height='404'} /uploads/allimg/1804/1-1P420103033-51.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103034.jpg' text='郑州惠民中学保洁' width='1133' height='714'} /uploads/allimg/1804/1-1P420103034.jpg {/dede:img}
