
<field:contact itemname="业主姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="业主性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:addr itemname="您的位置" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>

<field:area itemname="建筑人数" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:area>

<field:cost itemname="保洁预算" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cost>
