<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P420104222.jpg ",93,252);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P420104222.jpg";
$z[1][4]['text']="河南职工医院";
$z[1][4]['width']="768";
$z[1][4]['height']="537";
$z[2]=Array("img"," /uploads/allimg/1804/1-1P420104223.jpg ",254,413);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/1804/1-1P420104223.jpg";
$z[2][4]['text']="河南职工医院";
$z[2][4]['width']="960";
$z[2][4]['height']="720";

?>