{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/1804/1-1P4201H557.jpg' text='郑州惠民中学,郑州学校保洁' width='600' height='450'} /uploads/allimg/1804/1-1P4201H557.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P4201H557-50.jpg' text='郑州惠民中学,郑州学校保洁' width='600' height='450'} /uploads/allimg/1804/1-1P4201H557-50.jpg {/dede:img}
