<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P4201H557.jpg ",93,269);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P4201H557.jpg";
$z[1][4]['text']="郑州惠民中学,郑州学校保洁";
$z[1][4]['width']="600";
$z[1][4]['height']="450";
$z[2]=Array("img"," /uploads/allimg/1804/1-1P4201H557-50.jpg ",271,453);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/1804/1-1P4201H557-50.jpg";
$z[2][4]['text']="郑州惠民中学,郑州学校保洁";
$z[2][4]['width']="600";
$z[2][4]['height']="450";

?>