<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P420164R3.jpg ",93,275);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P420164R3.jpg";
$z[1][4]['text']="郑州市侯寨卫生院,郑州医院保洁";
$z[1][4]['width']="700";
$z[1][4]['height']="525";

?>