{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103406.jpg' text='河南省医药研究院附属医院保洁' width='600' height='402'} /uploads/allimg/1804/1-1P420103406.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103406-50.jpg' text='河南省医药研究院附属医院保洁' width='600' height='399'} /uploads/allimg/1804/1-1P420103406-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103406-51.jpg' text='河南省医药研究院附属医院保洁' width='600' height='402'} /uploads/allimg/1804/1-1P420103406-51.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103406-52.jpg' text='河南省医药研究院附属医院保洁' width='600' height='399'} /uploads/allimg/1804/1-1P420103406-52.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420103406-53.jpg' text='河南省医药研究院附属医院保洁' width='600' height='402'} /uploads/allimg/1804/1-1P420103406-53.jpg {/dede:img}
