{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/1804/1-1P420102010.jpg' text='郑州丹尼斯百货保洁' width='444' height='273'} /uploads/allimg/1804/1-1P420102010.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420102010-50.jpg' text='郑州丹尼斯百货保洁' width='187' height='114'} /uploads/allimg/1804/1-1P420102010-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420102011.jpg' text='郑州丹尼斯百货保洁' width='187' height='114'} /uploads/allimg/1804/1-1P420102011.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420102011-50.jpg' text='郑州丹尼斯百货保洁' width='187' height='114'} /uploads/allimg/1804/1-1P420102011-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/1804/1-1P420102011-51.jpg' text='郑州丹尼斯百货保洁' width='460' height='345'} /uploads/allimg/1804/1-1P420102011-51.jpg {/dede:img}
