<field:body itemname="个人简介" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:zhiwen itemname="职位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:zhiwen>
<field:jingyan itemname="工作年限" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:jingyan>
<field:zuopin itemname="代表作品" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:zuopin>

<field:jianjie itemname="设计理念" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:jianjie>