<field:pagestyle itemname="页面类型" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="设计理念" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:sheji itemname="设计" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:sheji>
<field:industry itemname="行业" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="机关单位,医院,学校,商场,银行,4S店,写字楼,企事业单位,其他"  maxlength="250" page="split">
</field:industry>
<field:leixing itemname="类型" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="欧式,中式,新古典,东南亚,美式,田园,地中海,现代,混搭"  maxlength="250" page="split">
</field:leixing>
<field:renshu itemname="人数" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="30-60㎡,60-90㎡,90-120㎡,120-140㎡,140-200㎡,200㎡以上"  maxlength="250" page="split">
</field:renshu>
<field:jltx itemname="负责人头像" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jltx>