<li>
							<a href="[field:arcurl/]">
								<div class="pic"><img src="[field:litpic/]"></div>
								<div class="desc clearfix">
									<div class="hd pull-right">
										<img src="[field:jltx/]" class="pull-left">
										[field:sheji/]									</div>
									<h3>[field:title/]</h3>
									<dl class="clearfix">
										<dd>[field:leixing/]</dd>
										<dd>[field:renshu/]</dd>
										<dd>[field:industry/]</dd>
									</dl>
								</div>
							</a>
						</li>