<channel:id>17</channel:id>
<channel:nid>article17</channel:nid>
<channel:typename>设计团队</channel:typename>
<channel:maintable>#@__archives</channel:maintable>
<channel:addtable>#@__addonarticle17</channel:addtable>
<channel:addcon>article_add.php</channel:addcon>
<channel:mancon>content_list.php</channel:mancon>
<channel:editcon>article_edit.php</channel:editcon>
<channel:useraddcon>article_add.php</channel:useraddcon>
<channel:usermancon>content_list.php</channel:usermancon>
<channel:usereditcon>article_edit.php</channel:usereditcon>
<channel:fieldset>
<field:body itemname="个人简介" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:zhiwen itemname="职位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:zhiwen>
<field:jingyan itemname="工作年限" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:jingyan>
<field:zuopin itemname="代表作品" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:zuopin>

<field:jianjie itemname="设计理念" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:jianjie>


</channel:fieldset>
<channel:listfields>body,zhiwen,jingyan,zuopin,jianjie</channel:listfields>
<channel:allfields></channel:allfields>
<channel:issystem>1</channel:issystem>
<channel:isshow>1</channel:isshow>
<channel:issend>1</channel:issend>
<channel:arcsta>-1</channel:arcsta>
<channel:usertype></channel:usertype>
<channel:sendrank>10</channel:sendrank>
<channel:isdefault>0</channel:isdefault>
<channel:needdes>1</channel:needdes>
<channel:needpic>1</channel:needpic>
<channel:titlename>标题</channel:titlename>
<channel:onlyone>0</channel:onlyone>
<channel:dfcid>0</channel:dfcid>
