<channel:id>18</channel:id>
<channel:nid>article18</channel:nid>
<channel:typename>在建工地</channel:typename>
<channel:maintable>#@__archives</channel:maintable>
<channel:addtable>#@__addonarticle18</channel:addtable>
<channel:addcon>article_add.php</channel:addcon>
<channel:mancon>content_list.php</channel:mancon>
<channel:editcon>article_edit.php</channel:editcon>
<channel:useraddcon>article_add.php</channel:useraddcon>
<channel:usermancon>content_list.php</channel:usermancon>
<channel:usereditcon>article_edit.php</channel:usereditcon>
<channel:fieldset>
<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:fengge itemname="风格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:fengge>
<field:mianji itemname="面积" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:mianji>
<field:huxing itemname="户型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:huxing>
<field:yezhu itemname="业主" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yezhu>
<field:jingcheng itemname="进度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jingcheng>

</channel:fieldset>
<channel:listfields>body,fengge,mianji,huxing,yezhu,jingcheng</channel:listfields>
<channel:allfields></channel:allfields>
<channel:issystem>1</channel:issystem>
<channel:isshow>1</channel:isshow>
<channel:issend>1</channel:issend>
<channel:arcsta>-1</channel:arcsta>
<channel:usertype></channel:usertype>
<channel:sendrank>10</channel:sendrank>
<channel:isdefault>0</channel:isdefault>
<channel:needdes>1</channel:needdes>
<channel:needpic>1</channel:needpic>
<channel:titlename>标题</channel:titlename>
<channel:onlyone>0</channel:onlyone>
<channel:dfcid>0</channel:dfcid>
