<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P4201A113.jpg ",93,281);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P4201A113.jpg";
$z[1][4]['text']="郑州艾格眼科医院保洁,郑州医院保洁";
$z[1][4]['width']="500";
$z[1][4]['height']="684";

?>