<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:fengge itemname="风格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:fengge>
<field:mianji itemname="面积" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:mianji>
<field:industry itemname="户型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:industry>
<field:yezhu itemname="业主" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yezhu>
<field:jingcheng itemname="进度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jingcheng>