<field:pagestyle itemname="页面类型" type="number" isnull="true" default="2" rename="" notsend="1" />
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>
<field:body itemname="管理理念" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:jingli itemname="经理" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="王效禹"  maxlength="250" page="split">
</field:jing>
