
<field:contact itemname="业主姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="业主性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:addr itemname="您的位置" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>

<field:area itemname="建筑面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:area>

<field:cost itemname="保洁预算" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cost>

<field:unit itemname="您的户型" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:unit>

<field:dstyle itemname="保洁风格" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dstyle>

<field:shejishi itemname="预约项目经理" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shejishi>

<field:content itemname="保洁要求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:dtime itemname="动工时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dtime>
