<li class="clearfix">
								<a href="[field:arcurl/]" class="pic pull-left"><img src="[field:litpic/]"></a>
								<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
								<h4><b>更新时间</b>：[field:pubdate function="GetDateMK(@me)"/]  <b>浏览人数</b>：[field:click/]</h4>
								<p>[field:description function='cn_substr(@me,185)'/]...</p>
								<a href="[field:arcurl/]" class="btn pull-right"></a>
							</li>