<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/1804/1-1P4201HQ2.jpg ",93,254);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/1804/1-1P4201HQ2.jpg";
$z[1][4]['text']="郑州电缆有限公司";
$z[1][4]['width']="600";
$z[1][4]['height']="450";
$z[2]=Array("img"," /uploads/allimg/1804/1-1P4201HQ3.jpg ",256,417);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/1804/1-1P4201HQ3.jpg";
$z[2][4]['text']="郑州电缆有限公司";
$z[2][4]['width']="600";
$z[2][4]['height']="523";

?>