<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>
<field:body itemname="管理理念" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:jingli itemname="经理" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="王效禹"  maxlength="250" page="split">
</field:jingli>
<field:industry itemname="行业" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="机关单位,医院,学校,商场,银行,4S店,写字楼,企事业单位,其他"  maxlength="250" page="split">
</field:industry>
<field:fengge itemname="风格" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="欧式,中式,新古典,东南亚,美式,田园,地中海,现代,混搭"  maxlength="250" page="split">
</field:fengge>
<field:renshu itemname="人数" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="1-5人,5-10人,10-20人,20-30人,40-50人50人以上"  maxlength="250" page="split">
</field:renshu>
<field:sjstx itemname="设计师头像" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjstx>