<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="设计理念" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:sheji itemname="设计" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="split">
</field:sheji>
<field:industry itemname="户型" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="一居,两居,三居,四居,复式,别墅,商用,其他"  maxlength="250" page="split">
</field:industry>
<field:fengge itemname="风格" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="欧式,中式,新古典,东南亚,美式,田园,地中海,现代,混搭"  maxlength="250" page="split">
</field:fengge>
<field:renshu itemname="面积" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="30-60㎡,60-90㎡,90-120㎡,120-140㎡,140-200㎡,200㎡以上"  maxlength="250" page="split">
</field:renshu>
<field:sjstx itemname="设计师头像" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjstx>