<?php
$z[0]=Array("field","",201,230);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("global","",231,257);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",301,352);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",391,413);
$z[3][4]=array();
$z[3][4]['name']="keywords";
$z[4]=Array("include","",955,990);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1115,1144);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n			\r\n				<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n				",1327,1531);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[7]=Array("field","",1607,1636);
$z[7][4]=array();
$z[7][4]['name']="typename";
$z[8]=Array("field","",1649,1670);
$z[8][4]=array();
$z[8][4]['name']="content";
$z[9]=Array("include","",1689,1726);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>