<?php
$z[0]=Array("field","",201,230);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("global","",231,257);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",301,352);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",391,413);
$z[3][4]=array();
$z[3][4]['name']="keywords";
$z[4]=Array("include","",955,990);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1166,1195);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n			\r\n				<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n				",1391,1595);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[7]=Array("list","\r\n									<li>\r\n						<a href=\"[field:arcurl/]\" class=\"pic\"><img src=\"[field:litpic/]\"></a>\r\n						<div class=\"desc clearfix\">\r\n							<h3><a href=\"[field:arcurl/]\">[field:title/]</a><span>[field:zhiwen/]</span></h3>\r\n							<a href=\"http://wpa.qq.com/msgrd?v=3&uin=[field:global.cfg_qq/]&site=qq&menu=yes\" class=\"btn pull-right\">在线咨询</a>\r\n							<p>[field:description function='cn_substr(@me,30)'/]</p>\r\n						</div>\r\n					</li>\r\n					",1748,2244);
$z[7][4]=array();
$z[7][4]['pagesize']="16";
$z[7][4]['titlelen']="60";
$z[8]=Array("pagelist","",2322,2393);
$z[8][4]=array();
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2419,2456);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>